/**
 * recipesPanel.js
 * Renders the Recipes tab.  The pattern selector options are generated by
 * looping over patternDefinitions so new patterns appear automatically.
 */

export function render(container) {
    const panel = document.createElement('div');
    panel.className = 'panel scrollable-panel';

    panel.innerHTML = `

        <fieldset>
            <legend>Explosion</legend>
            <div id="components-list"></div>
            <button id="add-component">Add Component</button>
        </fieldset>

        <fieldset class="recipe-settings">
            <legend>Name</legend>
            <div class="recipes-option">
                <input type="text" id="recipe-name" placeholder="Enter recipe name">
            </div>
        </fieldset>

        <fieldset class="recipe-actions">
            <button id="save-recipe">Save Recipe</button>
            <button id="randomize-recipe">Randomize Recipe</button>
            <button id="erase-recipes" class="danger-button">Erase All Recipes</button>
        </fieldset>

        <div class="saved-recipes">
            <h3>Saved Recipes</h3>
            <div id="recipe-list"></div>
        </div>
    `;

    container.appendChild(panel);
}
