export const AUTO_LAUNCHER_COST_BASE = 50;
export const AUTO_LAUNCHER_COST_RATIO = 2;

export const LAUNCHER_WORLD_HIGHLIGHT_DURATION = 2.5;

export const BUILDING_TYPES = {
    AUTO_LAUNCHER: {
        id: 'auto_launcher',
        name: 'Auto Launcher',
        description: 'Automatically launches fireworks',
        baseCost: AUTO_LAUNCHER_COST_BASE,
        costRatio: AUTO_LAUNCHER_COST_RATIO,
        currency: 'sparkles',
        width: 40,
        height: 20,
        y: -435,
        color: { r: 95 / 255, g: 101 / 255, b: 180 / 255, a: 1 },
        texture: null,
        textureKey: null,
        skeletonUrl: 'assets/skeletons/auto_launcher.json',
        skeletonScale: 10,
        baseSpawnInterval: 5,
        maxAccumulator: 200,
        unlockId: 'buildings_tab',
        statId: 'stat-bld-auto',
        panel: {
            showLauncherList: true,
            showSpreadButton: true,
            showRandomizeButton: true,
        },
        zIndex: 20,
    },
    RESOURCE_GENERATOR: {
        id: 'resource_generator',
        name: 'Sparkle Generator',
        description: 'Passively generates sparkles over time',
        baseCost: 400,
        costRatio: 1.45,
        currency: 'gold',
        width: 25,
        height: 30,
        y: -435,
        color: { r: 1, g: 0.84, b: 0, a: 1 },
        texture: null,
        textureKey: null,
        skeletonUrl: 'assets/skeletons/sparkle_generator.json',
        skeletonScale: 15,
        baseProductionRate: 1500.0,
        sparkleTrailBaseCount: 6,
        sparkleTrailScalingRatio: 0.25,
        maxSparkleTrailBurstCount: 100, 
        resourceType: 'sparkles',
        unlockId: 'resource_generator',
        statId: 'stat-bld-gen',
        maxAccumulator: 200,
        panel: {
            showLauncherList: false,
            showSpreadButton: false,
            showRandomizeButton: false,
        },
        zIndex: 10,
    },

    CATAPULT: {
        id: 'catapult',
        name: 'Catapult',
        description: 'Launches crowd members into the firework zone to catch sparkles',
        baseCost: 150,
        costRatio: 1.6,
        currency: 'gold',
        // Skeleton-rendered; width/height used for click-bounds only
        width: 120,
        height: 80,
        color: { r: 0.68, g: 0.68, b: 0.68, a: 1 },
        texture: null,
        textureKey: null,
        skeletonUrl: 'assets/skeletons/catapult.json',
        skeletonScale: 15,
        baseFireInterval: 5,
        // Position — to the left of the crowd so launched members arc into the fireworks zone
        x: -1400,
        y: -435,
        // Animation timing
        fireInterval: 6,   // seconds between shots (configurable)
        firingAnim: 'throwing',
        idleAnim: 'idle',
        // Rendering
        zIndex: 15,
        maxInstances: 20,  // 7 skeleton parts, but leave headroom
        unlockId: 'catapult',
        statId: 'stat-bld-catapult',
        panel: {
            showLauncherList: false,
            showSpreadButton: false,
            showRandomizeButton: false,
        },
    },

    DRONE_HUB: {
        id: 'drone_hub',
        name: 'Drone Hub',
        description: 'Periodically launches drones that collect firework particles',
        baseCost: 200,
        costRatio: 1.5,
        currency: 'gold',
        width: 40,
        height: 50,
        y: -435,
        color: { r: 0.2, g: 0.7, b: 1.0, a: 1 },
        texture: null,
        textureKey: null,
        skeletonUrl: 'assets/skeletons/drone_hub.json',
        skeletonScale: 20,
        baseSpawnInterval: 12,
        baseDroneLifetime: 10,
        baseDroneSpeed: 600,
        droneScale: 16,
        droneColor: { r: 0.1, g: 0.65, b: 0.8, a: 1.0 },
        unlockId: 'drone_hub',
        statId: 'stat-bld-drone',
        panel: {
            showLauncherList: false,
            showSpreadButton: false,
            showRandomizeButton: false,
        },
        zIndex: 12,
    }
};
