import { GAME_BOUNDS } from './GameBoundsConfig.js';

export const PROCEDURAL_BACKGROUND_CONFIG = {
    seed: 343597,
    bodyBackgroundColor: '#05070d',
    world: {
        xMin: GAME_BOUNDS.SCROLL_MIN_X - 1500,
        xMax: GAME_BOUNDS.SCROLL_MAX_X + 500,
        groundY: GAME_BOUNDS.WORLD_GROUND_Y,
        skyTopY: 760,
        groundDepth: 420,
        horizonY: GAME_BOUNDS.WORLD_GROUND_Y + 160,
    },
    zIndex: {
        sky: -2000,
        stars: -1995,
        treesFar: -1990,
        treesMid: -1985,
        treesNear: -1980,
        ground: -1970,
        groundRim: -1969,
    },
    sky: {
        gradientBands: 28,
        topColor: { r: 10 / 255, g: 18 / 255, b: 34 / 255, a: 1 },
        midColor: { r: 11 / 255, g: 16 / 255, b: 28 / 255, a: 1 },
        bottomColor: { r: 20 / 255, g: 20 / 255, b: 22 / 255, a: 1 },
        midStop: 0.58,
    },
    stars: {
        count: 400,
        distributionJitter: 10,
        minSize: 4,
        maxSize: 6,
        minAlpha: 0.2,
        maxAlpha: 0.82,
        minBrightness: .8,
        maxBrightness: 1,
        minYFromHorizon: 300,
        maxYFromSkyTop: 50,
        twinkleEnabled: true,
        twinkleMinSpeed: 0.35,
        twinkleMaxSpeed: 3.6,
        twinkleMinAmount: 0,
        twinkleMaxAmount: 2,
        twinkleAlphaInfluence: 1,
    },
    trees: {
        layers: [
            {
                treeCount: 200,
                baseY: GAME_BOUNDS.WORLD_GROUND_Y + 100,
                distributionJitter: 30,
                baseYJitter: 0,
                widthMin: 50,
                widthMax: 80,
                heightMin: 78,
                heightMax: 136,
                tierCountMin: 4,
                tierCountMax: 6,
                trunkHeightRatioMin: 0.1,
                trunkHeightRatioMax: 0.2,
                trunkWidthRatioMin: 0.12,
                trunkWidthRatioMax: 0.2,
                tierInnerRatioMin: 0.8,
                tierInnerRatioMax: 0.8,
                tierHeightJitterRatio: 0,
                tierWidthJitterRatio: 0,
                edgeJitter: 0,
                tipLeanRatioMin: 0,
                tipLeanRatioMax: 0,
                widthCurvePowerMin: 1,
                widthCurvePowerMax: 1,
                color: { r: 7 / 255, g: 9 / 255, b: 12 / 255, a: 1 },
            }
        ],
    },
    ground: {
        color: { r: 10 / 255, g: 12 / 255, b: 18 / 255, a: 1 },
        rimColor: { r: 28 / 255, g: 30 / 255, b: 36 / 255, a: 1 },
        rimHeight: 100,
    },
};
